name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # O la rama que uses para desplegar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # O la versión que requiera tu proyecto

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/hoja-de-vida  # Asegúrate de que esta ruta coincida con la carpeta generada por Angular
